### ISSUE TITLE
Cannot launch the server with an empty RtcConfig

### ISSUE THREAD

**Issue by rija1** [JoJoBond/3LAS#25]
I am trying to set this up on a local network and am therefore leaving the RtcConfig setting as null. I get an error when launching test.sh because of this it seems : 
node:internal/validators:163
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at normalizeSpawnArguments (node:child_process:545:3)
    at spawn (node:child_process:750:13)
    at new AFallbackProvider (/Users/reedz/websites/srts_streaming/3LAS/example/server/3las.server.js:316:50)
    at new FallbackProviderMp3 (/Users/reedz/websites/srts_streaming/3LAS/example/server/3las.server.js:333:9)
    at AFallbackProvider.Create (/Users/reedz/websites/srts_streaming/3LAS/example/server/3las.server.js:324:20)
    at new StreamServer (/Users/reedz/websites/srts_streaming/3LAS/example/server/3las.server.js:212:62)
    at StreamServer.Create (/Users/reedz/websites/srts_streaming/3LAS/example/server/3las.server.js:310:16)
    at Object.<anonymous> (/Users/reedz/websites/srts_streaming/3LAS/example/server/3las.server.js:421:29) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Any ideas ? Many thanks

**Comment by JoJoBond** [comment]
It doesn't select the right process name for ffmpeg.
What OS are you running it under?
It should be neither Windows nor Linux, it seems.

**Comment by rija1** [comment]
Oh right I'm using Mac OS. I tried with both "ffmpeg" and "/usr/local/bin/ffmpeg" as the FallbackFFmpegPath but got the same error.

**Comment by JoJoBond** [comment]
MacOS support is not tested. There are some minor code changes required:
3las.server.js line 40:

```
const FFmpeg_command = (() => {
    if (process.platform === 'win32')
        return Settings.FallbackFFmpegPath;
    else if (process.platform === 'linux')
        return "ffmpeg";
    else
        return Settings.FallbackFFmpegPath;
})();
```

Then FallbackFFmpegPath should work

**Comment by rija1** [comment]
Perfect, ffmpeg is running now, thank you!
