### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by ServeurpersoCom** [JoJoBond/3LAS#6]
Hello,

It's a pita to get working.
I installed ws and dependency :

```
        3LAS/
        node_modules/safe-buffer/
        node_modules/ultron/
        node_modules/ws/

```
Node version :
```
(root|/var/www) node -v
v8.4.0
(root|/var/www) npm -v
5.3.0

```

I succefuly configured the ffmpeg cmdline to my hardware (you must move the "-ac 1" argument to begin of the ffmpeg cmdline.)

```

ffmpeg -y -f alsa -ac 1 -i hw:2,0 -rtbufsize 64 -probesize 64 \
-acodec libmp3lame -ab 320k -reservoir 0 -f mp3 \
-fflags +nobuffer - \
| nodejs stdinstreamer.js -port 9601 -type mp3 -burstsize 1
```

Error log :

```

(root|/var/www/3LAS/server) ./robot.sh
ffmpeg version N-81539-gd2e7431 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --enable-gpl --enable-postproc --enable-swscale --enable-avfilter --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libx264 --enable-libspeex --enable-shared --enable-pthreads --enable-libopenjpeg --enable-libfaac --enable-nonfree --extra-libs=-lasound
  libavutil      55. 29.100 / 55. 29.100
  libavcodec     57. 54.102 / 57. 54.102
  libavformat    57. 48.102 / 57. 48.102
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 59.100 /  6. 59.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, alsa, from 'hw:2,0':
  Duration: N/A, start: 1503762482.264030, bitrate: 768 kb/s
    Stream #0:0: Audio: pcm_s16le, 48000 Hz, 1 channels, s16, 768 kb/s
[mp3 @ 0x2351c00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Output #0, mp3, to 'pipe:':
  Metadata:
    TSSE            : Lavf57.48.102
    Stream #0:0: Audio: mp3 (libmp3lame), 48000 Hz, mono, s16p, 320 kb/s
    Metadata:
      encoder         : Lavc57.54.102 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help

/var/www/node_modules/ws/index.js:9
const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/3LAS/server/stdinstreamer.js:7:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```

If I remove use strict from all scripts, I get the illegal use of reserved word "class" strange error:(

**Comment by JoJoBond** [comment]
You can replace 'const' with with 'var'.
This JavaScript is not written to be run in strict mode.
Disabling strict mode should make it work.

**Comment by JoJoBond** [comment]
Should be resolved as of https://github.com/JoJoBond/3LAS/commit/096fe04e175f157a3706f3cada4cec2ddc784911
